[Service]
NoNewPrivileges=false
RestrictAddressFamilies=
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX AF_NETLINK
ReadWritePaths=/etc/openap /etc/hostapd /etc/wpa_supplicant /etc/dnsmasq.d /etc/dnscrypt-proxy /etc/nftables.conf /etc/systemd/network /etc/systemd/system
